/* Generated By:JavaCC: Do not edit this line. StarParserConstants.java */
package EDU.bmrb.starlibj;

public interface StarParserConstants {

	int EOF = 0;
	int NONEOLN = 5;
	int LINENOSTARTINGSEMI = 6;
	int NONBLANK = 7;
	int BLANK = 8;
	int NONUNDERSCOREBLANK = 9;
	int EOLN_PRIV = 10;
	int LOOPSTART = 11;
	int GLOBALSTART = 12;
	int STOP = 13;
	int SAVEEND = 14;
	int DATASTART = 15;
	int SAVESTART = 16;
	int DVNFRAMECODE = 17;
	int TAGNAME = 18;
	int DVNSEMICOLON = 19;
	int DVNNON = 20;
	int DVNSINGLE = 22;
	int DVNDOUBLE = 25;

	int DEFAULT = 0;
	int SKIPTEXT_STATE = 1;
	int SQUOTESTATE = 2;
	int DQUOTESTATE = 3;

	String[] tokenImage = {
			"<EOF>",
			"<token of kind 1>",
			"<token of kind 2>",
			"<token of kind 3>",
			"<token of kind 4>",
			"<NONEOLN>",
			"<LINENOSTARTINGSEMI>",
			"<NONBLANK>",
			"<BLANK>",
			"<NONUNDERSCOREBLANK>",
			"<EOLN_PRIV>",
			"<LOOPSTART>",
			"<GLOBALSTART>",
			"<STOP>",
			"<SAVEEND>",
			"<DATASTART>",
			"<SAVESTART>",
			"<DVNFRAMECODE>",
			"<TAGNAME>",
			"<DVNSEMICOLON>",
			"<DVNNON>",
			"\"\\\'\"",
			"<DVNSINGLE>",
			"<token of kind 23>",
			"\"\\\"\"",
			"<DVNDOUBLE>",
			"<token of kind 26>",
			"\" \"",
			"\"\\t\"",
			"\"\\n\"",
			"\"\\r\"",
	};

}