PREFIX PDBo: <http://rdf.wwpdb.org/schema/pdbx-v50.owl#>

SELECT ?rcsb_id
FROM <http://rdf.wwpdb.org/pdb>
WHERE {

  BIND (IRI(CONCAT("http://rdf.wwpdb.org/pdb/", "2K8D", "/database_2Category")) AS ?pdb_db2c)

  ?pdb_db2c PDBo:has_database_2 ?rcsb_s .

  FILTER (CONTAINS(STR(?rcsb_s), "RCSB"))

  ?rcsb_s PDBo:database_2.database_code ?rcsb_id .

}
