PREFIX PDBo: <http://rdf.wwpdb.org/schema/pdbx-v40.owl#>

SELECT ?pubmed_id
FROM <http://rdf.wwpdb.org/pdb>
WHERE {

  BIND (IRI(CONCAT("http://rdf.wwpdb.org/pdb/", "2MAO", "/citation/primary")) AS ?pdb_cp)

  ?pdb_cp PDBo:citation.pdbx_database_id_PubMed ?pubmed_id .

}
